const emojis = [
    { emoji: "🎁", name: "Wrapped Gift" },
    { emoji: "🎉", name: "Party Popper" },
    { emoji: "🍰", name: "Birthday Cake" },
    { emoji: "🍫", name: "Chocolate Bar" },
    { emoji: "🌹", name: "Rose" },
    { emoji: "📚", name: "Books" },
    { emoji: "🎨", name: "Artist Palette" },
    { emoji: "💎", name: "Gem Stone" },
    { emoji: "🎈", name: "Balloon" },
    { emoji: "🧸", name: "Teddy Bear" },
    { emoji: "🎮", name: "Video Game Controller" },
    { emoji: "🎵", name: "Musical Note" },
    { emoji: "🍩", name: "Doughnut" },
    { emoji: "🍬", name: "Candy" },
    { emoji: "🧁", name: "Cupcake" },
    { emoji: "🥂", name: "Clinking Glasses" },
    { emoji: "📷", name: "Camera" },
    { emoji: "💻", name: "Laptop" },
    { emoji: "🎸", name: "Guitar" },
    { emoji: "🔑", name: "Key" },
    { emoji: "🎀", name: "Ribbon" },
    { emoji: "🎊", name: "Confetti Ball" },
    { emoji: "🍭", name: "Lollipop" },
    { emoji: "🌺", name: "Hibiscus" },
    { emoji: "📖", name: "Open Book" },
    { emoji: "🖌️", name: "Paintbrush" },
    { emoji: "💍", name: "Ring" },
    { emoji: "🎪", name: "Circus Tent" },
    { emoji: "🧩", name: "Puzzle Piece" },
    { emoji: "🚀", name: "Rocket" },
    { emoji: "🎩", name: "Top Hat" },
    { emoji: "💼", name: "Briefcase" },
    { emoji: "🎧", name: "Headphone" },
    { emoji: "🕶️", name: "Sunglasses" },
    { emoji: "👑", name: "Crown" },
    { emoji: "🌈", name: "Rainbow" },
    { emoji: "📱", name: "Mobile Phone" },
    { emoji: "🚲", name: "Bicycle" },
    { emoji: "⌚", name: "Watch" },
    { emoji: "📸", name: "Camera with Flash" },
    { emoji: "🎬", name: "Clapper Board" },
    { emoji: "💡", name: "Light Bulb" },
    { emoji: "💰", name: "Money Bag" },
    { emoji: "🎶", name: "Musical Notes" },
    { emoji: "🔒", name: "Locked" },
    { emoji: "🛒", name: "Shopping Cart" },
    { emoji: "🔨", name: "Hammer" },
    { emoji: "🎤", name: "Microphone" },
    { emoji: "🕯️", name: "Candle" },
    { emoji: "🧨", name: "Firecracker" },
    { emoji: "🔦", name: "Flashlight" },
    { emoji: "🧰", name: "Toolbox" },
    { emoji: "📡", name: "Satellite" },
    { emoji: "🛁", name: "Bathtub" },
    { emoji: "🎣", name: "Fishing Pole" },
    { emoji: "🎳", name: "Bowling" },
    { emoji: "🎰", name: "Slot Machine" },
    { emoji: "🧦", name: "Socks" },
    { emoji: "🧤", name: "Gloves" },
    { emoji: "🧣", name: "Scarf" },
    { emoji: "🎃", name: "Jack-O-Lantern" },
    { emoji: "🎄", name: "Christmas Tree" },
    { emoji: "🎅", name: "Santa Claus" },
    { emoji: "🎆", name: "Fireworks" },
    { emoji: "🎇", name: "Sparkler" },
    { emoji: "🧨", name: "Firecracker" },
    { emoji: "🎈", name: "Balloon" },
    { emoji: "💐", name: "Bouquet" },
    { emoji: "🌸", name: "Cherry Blossom" },
    { emoji: "💮", name: "White Flower" },
    { emoji: "🏵️", name: "Rosette" },
    { emoji: "🌹", name: "Rose" },
    { emoji: "🥀", name: "Wilted Flower" },
    { emoji: "🌺", name: "Hibiscus" },
    { emoji: "🌻", name: "Sunflower" },
    { emoji: "🌼", name: "Blossom" },
    { emoji: "🌷", name: "Tulip" },
    { emoji: "🌱", name: "Seedling" },
    { emoji: "🌲", name: "Evergreen Tree" },
    { emoji: "🌳", name: "Deciduous Tree" },
    { emoji: "🌴", name: "Palm Tree" },
    { emoji: "🌵", name: "Cactus" },
    { emoji: "🌾", name: "Sheaf of Rice" },
    { emoji: "🌿", name: "Herb" },
    { emoji: "☘️", name: "Shamrock" },
    { emoji: "🍀", name: "Four Leaf Clover" },
    { emoji: "🍁", name: "Maple Leaf" },
    // Add more objects here as needed
    { emoji: "🍔", name: "Hamburger" },
    { emoji: "🍟", name: "French Fries" },
    { emoji: "🍕", name: "Pizza" },
    { emoji: "🥪", name: "Sandwich" },
    { emoji: "🌭", name: "Hot Dog" },
    { emoji: "🥙", name: "Stuffed Flatbread" },
    { emoji: "🧆", name: "Falafel" },
    { emoji: "🌮", name: "Taco" },
    { emoji: "🌯", name: "Burrito" },
    { emoji: "🥗", name: "Green Salad" },
    { emoji: "🥘", name: "Shallow Pan of Food" },
    { emoji: "🍲", name: "Pot of Food" },
    { emoji: "🥣", name: "Bowl with Spoon" },
    { emoji: "🍛", name: "Curry Rice" },
    { emoji: "🍜", name: "Steaming Bowl" },
    { emoji: "🍝", name: "Spaghetti" },
    { emoji: "🍠", name: "Roasted Sweet Potato" },
    { emoji: "🍢", name: "Oden" },
    { emoji: "🍣", name: "Sushi" },
    { emoji: "🍤", name: "Fried Shrimp" },
    { emoji: "🍥", name: "Fish Cake with Swirl" },
    { emoji: "🥮", name: "Moon Cake" },
    { emoji: "🍡", name: "Dango" },
    { emoji: "🥟", name: "Dumpling" },
    { emoji: "🥠", name: "Fortune Cookie" },
    { emoji: "🥡", name: "Takeout Box" },
    { emoji: "🥧", name: "Pie" },
    { emoji: "🧁", name: "Cupcake" },
    { emoji: "🍰", name: "Shortcake" },
    { emoji: "🎂", name: "Birthday Cake" },
    { emoji: "🍮", name: "Custard" },
    { emoji: "🍩", name: "Doughnut" },
    { emoji: "🍪", name: "Cookie" },
    { emoji: "🎃", name: "Jack-O-Lantern" },
    { emoji: "🍭", name: "Lollipop" },
    { emoji: "🍬", name: "Candy" },
    { emoji: "🍫", name: "Chocolate Bar" },
    { emoji: "🍿", name: "Popcorn" },
    { emoji: "🍩", name: "Doughnut" },
    { emoji: "🥤", name: "Cup with Straw" },
    { emoji: "🍺", name: "Beer Mug" },
    { emoji: "🍷", name: "Wine Glass" },
    { emoji: "🍹", name: "Tropical Drink" },
    { emoji: "🥂", name: "Clinking Glasses" },
    { emoji: "🍾", name: "Bottle with Popping Cork" },
    { emoji: "🥃", name: "Tumbler Glass" },
    { emoji: "🍸", name: "Cocktail Glass" },
    { emoji: "🍻", name: "Clinking Beer Mugs" },
    { emoji: "🍶", name: "Sake" },
    { emoji: "🍵", name: "Teacup Without Handle" },
    { emoji: "🥄", name: "Spoon" },
    { emoji: "🍴", name: "Fork and Knife" },
    { emoji: "🥢", name: "Chopsticks" },
  ];
  

  export default emojis;
  